### ISSUE TITLE
Adding the data folder with a sample or truncated version of the Parquet file 

### ISSUE THREAD

**Issue by jefkine** [profitviews/fast-python-backtest#17]
Is it possible to include a sample or truncated version of the Parquet file '20221109.parquet' to help with further testing of the cloned versions of the code and also, some familiarity with the parquet files? Thanks

**Comment by rthickling** [comment]
Yes, looking for an effective solution for this:
- adding a representative file via a Github system for large files
- adding code to generate a reasonable file (C++ or Python)
- adding code to read from AWS S3 and providing a public file there

It's not hard - will get it done.
